<?php namespace RKooistra\SuperEloquentRepository\Tests\Unit;

use Illuminate\Foundation\Testing\TestCase;
use RKooistra\SuperEloquentRepository\Abstracts\ConcreteResourceRepository;

/**
 * Class ResourceRepositoryUnitTest
 * @package Tests\Unit
 */
class ResourceRepository_UnitTest extends \PHPUnit\Framework\TestCase
{
    private static $_sut;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::$_sut = new ConcreteResourceRepository_Stub();
    }

    public function test_connection_setters_and_getters() {
        self::$_sut->setConnection('foo');
        $this->assertEquals('foo', self::$_sut->getConnection());
        self::$_sut->setConnection('bar');
        $this->assertEquals('bar', self::$_sut->getConnection());
    }
}

class ConcreteResourceRepository_Stub extends ConcreteResourceRepository
{
    /** @return string <Return the full path to the class here.> */
    protected function getModelClass(): string {
        return self::class;
    }
}
